/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ksc_sdk_core_update_PatchClient */

#ifndef _Included_com_ksc_client_update
#define _Included_com_ksc_client_update
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ksc_client_update_PatchClient
 * Method:    applyPatchToOldApk
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint
JNICALL Java_com_ksc_client_update_PatchClient_applyPatchToOldApk(JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
